### ISSUE TITLE
Install from source failing on Windows 7 64bit with R-3.5.0 & Rtools 3.5

### ISSUE THREAD

**Issue by aadler** [RcppCore/RcppParallel#64]
When installing RcppParallel from source, I get the error described below. Rcpp installed properly, and RcppParallel isntalled fine on the same machine using R 3.4.x and Rtools 3.4.

```
> install.packages('RcppParallel', type = 'source', INSTALL_opts = '--byte-compile --clean --resave-data --compact-docs')
trying URL 'https://cran.rstudio.com/src/contrib/RcppParallel_4.4.0.tar.gz'
Content type 'application/x-gzip' length 1264395 bytes (1.2 MB)
downloaded 1.2 MB

'\\[redacted]'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'RcppParallel' ...
** package 'RcppParallel' successfully unpacked and MD5 sums checked
* preparing to configure package 'RcppParallel' ...
** configured file: 'src/Makevars.in' => 'src/Makevars'
* finished configure for package 'RcppParallel'
** libs
mkdir -p ../inst/lib/x64/; \
cd tbb/src; \
if [ -n "" ]; then \
   CYGWIN=nodosfilewarning CONLY="c:/Rtools/mingw_64/bin/gcc " CPLUS="c:/Rtools/mingw_64/bin/g++ " PIC_KEY="" WARNING_SUPPRESS="" make -e stdver=c++0x compiler=clang CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib rtools=true compiler=gcc arch=intel64; \
elif [ -n "c:/Rtools/mingw_64/bin/gcc" ]; then \
   CYGWIN=nodosfilewarning CONLY="c:/Rtools/mingw_64/bin/gcc " CPLUS="c:/Rtools/mingw_64/bin/g++ " PIC_KEY="" WARNING_SUPPRESS="" make -e stdver=c++0x compiler=gcc CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib rtools=true compiler=gcc arch=intel64; \
else \
   CYGWIN=nodosfilewarning CONLY="c:/Rtools/mingw_64/bin/gcc " CPLUS="c:/Rtools/mingw_64/bin/g++ " PIC_KEY="" WARNING_SUPPRESS="" make -e stdver=c++0x CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib rtools=true compiler=gcc arch=intel64; \
fi; \
cd ../..; \
cp tbb/build/lib_release/tbb*.dll ../inst/lib/x64/
make[1]: Entering directory '/R/temp/RtmpspyhPJ/R.INSTALL29cc7f73328f/RcppParallel/src/tbb/src'
Created ../build/lib_release directory
make -C "../build/lib_release"  -r -f ../../build/Makefile.tbb cfg=release
make[2]: Entering directory '/R/temp/RtmpspyhPJ/R.INSTALL29cc7f73328f/RcppParallel/src/tbb/build/lib_release'
../../build/Makefile.tbb:32: CONFIG: cfg=release arch=intel64 compiler=gcc target=windows runtime=mingw4.9.3
c:/Rtools/mingw_64/bin/g++  -o concurrent_hash_map.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_hash_map.cpp
c:/Rtools/mingw_64/bin/g++  -o concurrent_queue.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_queue.cpp
c:/Rtools/mingw_64/bin/g++  -o concurrent_vector.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_vector.cpp
c:/Rtools/mingw_64/bin/g++  -o dynamic_link.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/dynamic_link.cpp
c:/Rtools/mingw_64/bin/g++  -o itt_notify.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/itt_notify.cpp
c:/Rtools/mingw_64/bin/g++  -o cache_aligned_allocator.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/cache_aligned_allocator.cpp
c:/Rtools/mingw_64/bin/g++  -o pipeline.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/pipeline.cpp
c:/Rtools/mingw_64/bin/g++  -o queuing_mutex.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/queuing_mutex.cpp
c:/Rtools/mingw_64/bin/g++  -o queuing_rw_mutex.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/queuing_rw_mutex.cpp
c:/Rtools/mingw_64/bin/g++  -o reader_writer_lock.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/reader_writer_lock.cpp
c:/Rtools/mingw_64/bin/g++  -o spin_rw_mutex.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/spin_rw_mutex.cpp
c:/Rtools/mingw_64/bin/g++  -o x86_rtm_rw_mutex.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/x86_rtm_rw_mutex.cpp
c:/Rtools/mingw_64/bin/g++  -o spin_mutex.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/spin_mutex.cpp
c:/Rtools/mingw_64/bin/g++  -o critical_section.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/critical_section.cpp
c:/Rtools/mingw_64/bin/g++  -o mutex.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/mutex.cpp
c:/Rtools/mingw_64/bin/g++  -o recursive_mutex.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/recursive_mutex.cpp
c:/Rtools/mingw_64/bin/g++  -o condition_variable.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/condition_variable.cpp
c:/Rtools/mingw_64/bin/g++  -o tbb_thread.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/tbb_thread.cpp
c:/Rtools/mingw_64/bin/g++  -o concurrent_monitor.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_monitor.cpp
c:/Rtools/mingw_64/bin/g++  -o semaphore.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/semaphore.cpp
c:/Rtools/mingw_64/bin/g++  -o private_server.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/private_server.cpp
c:/Rtools/mingw_64/bin/g++  -o rml_tbb.o -c -MMD -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/rml/client/rml_tbb.cpp
"C:/windows/system32/cmd.exe" /C cscript /nologo /E:jscript ../../build/version_info_windows.js gcc intel64 "c:/Rtools/mingw_64/bin/g++  -g -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x -I../../src -I../../src/rml/include -I../../include -I." > version_string.ver
make[2]: *** [../../build/common_rules.inc:165: version_string.ver] Error 1
make[2]: *** Deleting file 'version_string.ver'
make[2]: Leaving directory '/R/temp/RtmpspyhPJ/R.INSTALL29cc7f73328f/RcppParallel/src/tbb/build/lib_release'
make[1]: *** [Makefile:104: tbb_release] Error 2
make[1]: Leaving directory '/R/temp/RtmpspyhPJ/R.INSTALL29cc7f73328f/RcppParallel/src/tbb/src'
cp: cannot stat 'tbb/build/lib_release/tbb*.dll': No such file or directory
make: *** [Makevars:73: tbb] Error 1
ERROR: compilation failed for package 'RcppParallel'
* removing 'C:/R/RCurrent/R-3.5.0/library/RcppParallel'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘RcppParallel’ had non-zero exit status
```

Session Info:
```

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.12.16

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0    yaml_2.1.18  
```

I note that httpuv issues have had bearing on RcppParallel, so I'll note I have an issue with that as well: https://github.com/rstudio/httpuv/issues/126

Thank you.

**Comment by kevinushey** [comment]
Thanks -- I was able to reproduce this on my Windows VM, but I'm out of office until early May so won't have time to look into this until then.

**Comment by sgsokol** [comment]
It also fails to build on my Linux fresh R-3.5.0 compiled from sources.
Example of compilation command (which succeds) is
```
g++ -o tbb_main.o -c -MMD -DDO_ITT_NOTIFY -g -O2 -DUSE_PTHREAD -m64 -mrtm    -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/tbb_main.cpp
```
And faulty command and error message are:
```
g++  -o libtbb.so.2 concurrent_hash_map.o concurrent_queue.o concurrent_vector.o dynamic_link.o itt_notify.o cache_aligned_allocator.o pipeline.o queuing_mutex.o queuing_rw_mutex.o reader_writer_lock.o spin_rw_mutex.o x86_rtm_rw_mutex.o spin_mutex.o critical_section.o mutex.o recursive_mutex.o condition_variable.o tbb_thread.o concurrent_monitor.o semaphore.o private_server.o rml_tbb.o tbb_misc.o tbb_misc_ex.o task.o task_group_context.o governor.o market.o arena.o scheduler.o observer_proxy.o tbb_statistics.o tbb_main.o    -ldl -lpthread -lrt -shared -Wl,-soname=libtbb.so.2 -m64  -Wl,--version-script,tbb.def
/usr/bin/ld: concurrent_queue.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
concurrent_queue.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```
So, the problem seems to be lacking `-fPIC` or `-fpic` flag. Note that it is not R config's fault which gives:
```
R CMD config CPICFLAGS
-fPIC
```
By the way, the first command above seems to ignore `PKG_CXXFLAGS` which in my case is set in ~/.R/Makevars as follows:
```
PKG_CXXFLAGS += -fPIC -O3 -mtune=native -march=native -std=c++11
```
Instead of this we see `-g -O2` and `-std=c++0x`. I suppose these options are hardwired in your makefile?

My 0.02€

**Comment by aadler** [comment]
Any updates, @kevinushey ?

**Comment by kevinushey** [comment]
Sorry, I lost track of this one! I'll try to take a look tomorrow / early next week.

**Comment by kevinushey** [comment]
This should be fixed up with https://github.com/RcppCore/RcppParallel/commit/9f839430163e64122f46fdf29aef26eeaee7c3d3 -- can you give the latest development version a shot and let me know?

**Comment by kevinushey** [comment]
@sgsokol if you're still having trouble can you please file a separate issue?

**Comment by aadler** [comment]
@kevinushey Yes. RcppParallel installed correctly using 9f83943. However, now my package which depends on RcppParallel is acting up. I'm getting

```
init.o:init.c:(.rdata+0x88): undefined reference to `lamW_lambertW0_C'
init.o:init.c:(.rdata+0xa0): undefined reference to `lamW_lambertWm1_C'
init.o:init.c:(.rdata+0xb8): undefined reference to `lamW_RcppExport_registerCCallable'
```
which means something isn't right in the automatic file creation of RcppParallel, but that's for a different issue. Thanks!

**Comment by aadler** [comment]
Never mind that last. It was a problem from a failed build. Cleaning out the old cpp's and o's has it compile properly for now.

**Comment by sgsokol** [comment]
@kevinushey as requested, new issue #69 is just filed.

**Comment by aadler** [comment]
@kevinushey, should we close this now?

**Comment by kevinushey** [comment]
Yes, I think we can close this now.
