### ISSUE TITLE
Install/compile fail  RcppParallel

### ISSUE THREAD

**Issue by Woong-jae-Jung** [RcppCore/RcppParallel#62]
Hi,

I'm trying to install RcppParallel in R but have trouble going on...

When I install RcppParallel(to use other packages), I fail and get error message.
The message is below.

**`../../build/common_rules.inc:77: recipe for target 'concurrent_queue.o' failed
make[2]: Leaving directory '/tmp/RtmpmRJwWk/R.INSTALL2f6866abe3b03/RcppParallel/src/tbb/build/lib_release'
make[2]: *** [concurrent_queue.o] Error 1
Makefile:101: recipe for target 'tbb_release' failed
make[1]: *** [tbb_release] Error 2
make[1]: Leaving directory '/tmp/RtmpmRJwWk/R.INSTALL2f6866abe3b03/RcppParallel/src/tbb/src'
cp: cannot stat 'tbb/build/lib_release/libtbb*.*': No such file or directory
Makevars:74: recipe for target 'tbb' failed
make: *** [tbb] Error 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/usr/local/lib/R/site-library/RcppParallel’
* restoring previous ‘/usr/local/lib/R/site-library/RcppParallel’
Warning in install.packages :
  installation of package ‘RcppParallel’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpibrveZ/downloaded_packages’`**

I tried to fix it, but I'm not very good at debuging I guess...

Could someone help me, please??

**Comment by eddelbuettel** [comment]
We need more details. What is your architecture / OS?  Anything else unusual?

**Comment by Woong-jae-Jung** [comment]
My OS is ubuntu 16.04

And I see nothing unusual.

I guess I had similar issue in the past installing same package. In that time, I remember that I had to install tbb. This time, I was actually updating rcppparallel package while installing new R package.

**Comment by eddelbuettel** [comment]
I happen to develop on Ubuntu, currently 17.10, and have used every other version before that.

You will have to provide much more complete and _reproducible_ examples.  Maybe you're just low on ram.  We can't tell.  And when we can't tell we can't help.

**Comment by Woong-jae-Jung** [comment]
May be the full process might help??..

```
mkdir -p ../inst/lib/; \
cd tbb/src; \
if [ -n "" ]; then \
   make cpp0x=1 compiler=clang CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
elif [ -n "gcc -std=gnu99" ]; then \
   make cpp0x=1 compiler=gcc CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
else \
   make cpp0x=1 CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
fi; \
cd ../..; \
cp tbb/build/lib_release/libtbb*.* ../inst/lib/
make[1]: Entering directory '/tmp/RtmpOpbO1A/R.INSTALL254444c12a42/RcppParallel/src/tbb/src'
Created ../build/lib_release directory
make -C "../build/lib_release"  -r -f ../../build/Makefile.tbb cfg=release
make[2]: Entering directory '/tmp/RtmpOpbO1A/R.INSTALL254444c12a42/RcppParallel/src/tbb/build/lib_release'
../../build/Makefile.tbb:31: CONFIG: cfg=release arch=intel64 compiler=gcc target=linux runtime=cc6.3.0_libc2.23_kernel4.4.0
g++ -o concurrent_hash_map.o -c -MMD -DDO_ITT_NOTIFY -g -O2 -DUSE_PTHREAD -m64  -fPIC -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x -D_TBB_CPP0X  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_hash_map.cpp
g++ -o concurrent_queue.o -c -MMD -DDO_ITT_NOTIFY -g -O2 -DUSE_PTHREAD -m64  -fPIC -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x -D_TBB_CPP0X  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_queue.cpp
In file included from ../../src/tbb/concurrent_monitor.h:30:0,
                 from ../../src/tbb/concurrent_queue.cpp:27:
../../src/tbb/semaphore.h:115:5: error: ‘sem_t’ does not name a type
     sem_t sem;
     ^~~~~
../../src/tbb/semaphore.h: In destructor ‘tbb::internal::semaphore::~semaphore()’:
../../src/tbb/semaphore.h:104:33: error: ‘sem’ was not declared in this scope
         int ret = sem_destroy( &sem );
                                 ^~~
../../src/tbb/semaphore.h:104:37: error: ‘sem_destroy’ was not declared in this scope
         int ret = sem_destroy( &sem );
                                     ^
../../src/tbb/semaphore.h: In member function ‘void tbb::internal::semaphore::P()’:
../../src/tbb/semaphore.h:109:27: error: ‘sem’ was not declared in this scope
         while( sem_wait( &sem )!=0 )
                           ^~~
../../src/tbb/semaphore.h:109:31: error: ‘sem_wait’ was not declared in this scope
         while( sem_wait( &sem )!=0 )
                               ^
../../src/tbb/semaphore.h: In member function ‘void tbb::internal::semaphore::V()’:
../../src/tbb/semaphore.h:113:27: error: ‘sem’ was not declared in this scope
     void V() { sem_post( &sem ); }
                           ^~~
../../src/tbb/semaphore.h:113:31: error: ‘sem_post’ was not declared in this scope
     void V() { sem_post( &sem ); }
                               ^
../../src/tbb/semaphore.h: In member function ‘void tbb::internal::semaphore::init_semaphore(int)’:
../../src/tbb/semaphore.h:117:30: error: ‘sem’ was not declared in this scope
         int ret = sem_init( &sem, /*shared among threads*/ 0, start_cnt_ );
                              ^~~
../../src/tbb/semaphore.h:117:74: error: ‘sem_init’ was not declared in this scope
         int ret = sem_init( &sem, /*shared among threads*/ 0, start_cnt_ );
                                                                          ^
../../src/tbb/concurrent_queue.cpp: In member function ‘tbb::internal::concurrent_queue_base_v3::page* tbb::internal::micro_queue::make_copy(tbb::internal::concurrent_queue_base&, const tbb::internal::concurrent_queue_base_v3::page*, std::size_t, std::size_t, tbb::internal::ticket&, tbb::internal::concurrent_queue_base_v3::copy_specifics)’:
../../src/tbb/concurrent_queue.cpp:316:11: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
         if( new_page->mask & uintptr_t(1)<<begin_in_page )
           ^
../../build/common_rules.inc:77: recipe for target 'concurrent_queue.o' failed
make[2]: Leaving directory '/tmp/RtmpOpbO1A/R.INSTALL254444c12a42/RcppParallel/src/tbb/build/lib_release'
make[2]: *** [concurrent_queue.o] Error 1
Makefile:101: recipe for target 'tbb_release' failed
make[1]: *** [tbb_release] Error 2
make[1]: Leaving directory '/tmp/RtmpOpbO1A/R.INSTALL254444c12a42/RcppParallel/src/tbb/src'
cp: cannot stat 'tbb/build/lib_release/libtbb*.*': No such file or directory
Makevars:74: recipe for target 'tbb' failed
make: *** [tbb] Error 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/usr/local/lib/R/site-library/RcppParallel’
* restoring previous ‘/usr/local/lib/R/site-library/RcppParallel’
Warning in install.packages :
  installation of package ‘RcppParallel’ had non-zero exit status
```

These are the full processing of updating RcppParallel package.
Process tells me that somethings are not declared in the scope.
Could that be the starting of installation failure?

Thank you for the reply.

**Comment by eddelbuettel** [comment]
Still not complete.  If I have I take a look at work on a 16.04 machine.

**Comment by eddelbuettel** [comment]
I just install RcppParallel (from CRAN) without a hitch on a standard 16.04 machine.  

We will need more details from you, and I would recommend you try to dive into individual subcommands of the Makevars we ship.

**Comment by eddelbuettel** [comment]
I just fired up a vanilla ubuntu:16.04 Docker container, installed `r-cran-rcpp` following an initial update of the apt cache info, and then ran 

```sh
R -e 'install.packages("RcppParallel", repos="http://cloud.r-project.org")'
```

without a hitch.  So there is _still_ nothing reproducible here.

**Comment by Woong-jae-Jung** [comment]
Could you tell me the meaning of "dive into individual subcommands of the Makevars we ship"??
Sorry for the poor English, so I don't understand it quite well...

I tried both of ways you suggested, and get the same errors.
I just ran single command to install the package.

```
R -e 'install.packages("RcppParallel", repos="http://cloud.r-project.org")'

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("RcppParallel", repos="http://cloud.r-project.org")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'http://cloud.r-project.org/src/contrib/RcppParallel_4.3.20.2.tar.gz'
Content type 'application/x-gzip' length 1561385 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

* installing *source* package ‘RcppParallel’ ...
** package ‘RcppParallel’ successfully unpacked and MD5 sums checked
** libs
mkdir -p ../inst/lib/; \
cd tbb/src; \
if [ -n "" ]; then \
   make cpp0x=1 compiler=clang CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
elif [ -n "gcc -std=gnu99" ]; then \
   make cpp0x=1 compiler=gcc CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
else \
   make cpp0x=1 CXXFLAGS=-DTBB_NO_LEGACY=1 tbb_release tbbmalloc_release tbb_build_prefix=lib; \
fi; \
cd ../..; \
cp tbb/build/lib_release/libtbb*.* ../inst/lib/
make[1]: Entering directory '/tmp/RtmpZHlh9r/R.INSTALL186656a92e3c/RcppParallel/src/tbb/src'
Created ../build/lib_release directory
make -C "../build/lib_release"  -r -f ../../build/Makefile.tbb cfg=release
make[2]: Entering directory '/tmp/RtmpZHlh9r/R.INSTALL186656a92e3c/RcppParallel/src/tbb/build/lib_release'
../../build/Makefile.tbb:31: CONFIG: cfg=release arch=intel64 compiler=gcc target=linux runtime=cc6.3.0_libc2.23_kernel4.4.0
g++ -o concurrent_hash_map.o -c -MMD -DDO_ITT_NOTIFY -g -O2 -DUSE_PTHREAD -m64  -fPIC -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x -D_TBB_CPP0X  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_hash_map.cpp
g++ -o concurrent_queue.o -c -MMD -DDO_ITT_NOTIFY -g -O2 -DUSE_PTHREAD -m64  -fPIC -D__TBB_BUILD=1 -Wall  -DTBB_NO_LEGACY=1 -std=c++0x -D_TBB_CPP0X  -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_queue.cpp
In file included from ../../src/tbb/concurrent_monitor.h:30:0,
                 from ../../src/tbb/concurrent_queue.cpp:27:
../../src/tbb/semaphore.h:115:5: error: ‘sem_t’ does not name a type
     sem_t sem;
     ^~~~~
../../src/tbb/semaphore.h: In destructor ‘tbb::internal::semaphore::~semaphore()’:
../../src/tbb/semaphore.h:104:33: error: ‘sem’ was not declared in this scope
         int ret = sem_destroy( &sem );
                                 ^~~
../../src/tbb/semaphore.h:104:37: error: ‘sem_destroy’ was not declared in this scope
         int ret = sem_destroy( &sem );
                                     ^
../../src/tbb/semaphore.h: In member function ‘void tbb::internal::semaphore::P()’:
../../src/tbb/semaphore.h:109:27: error: ‘sem’ was not declared in this scope
         while( sem_wait( &sem )!=0 )
                           ^~~
../../src/tbb/semaphore.h:109:31: error: ‘sem_wait’ was not declared in this scope
         while( sem_wait( &sem )!=0 )
                               ^
../../src/tbb/semaphore.h: In member function ‘void tbb::internal::semaphore::V()’:
../../src/tbb/semaphore.h:113:27: error: ‘sem’ was not declared in this scope
     void V() { sem_post( &sem ); }
                           ^~~
../../src/tbb/semaphore.h:113:31: error: ‘sem_post’ was not declared in this scope
     void V() { sem_post( &sem ); }
                               ^
../../src/tbb/semaphore.h: In member function ‘void tbb::internal::semaphore::init_semaphore(int)’:
../../src/tbb/semaphore.h:117:30: error: ‘sem’ was not declared in this scope
         int ret = sem_init( &sem, /*shared among threads*/ 0, start_cnt_ );
                              ^~~
../../src/tbb/semaphore.h:117:74: error: ‘sem_init’ was not declared in this scope
         int ret = sem_init( &sem, /*shared among threads*/ 0, start_cnt_ );
                                                                          ^
../../src/tbb/concurrent_queue.cpp: In member function ‘tbb::internal::concurrent_queue_base_v3::page* tbb::internal::micro_queue::make_copy(tbb::internal::concurrent_queue_base&, const tbb::internal::concurrent_queue_base_v3::page*, std::size_t, std::size_t, tbb::internal::ticket&, tbb::internal::concurrent_queue_base_v3::copy_specifics)’:
../../src/tbb/concurrent_queue.cpp:316:11: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
         if( new_page->mask & uintptr_t(1)<<begin_in_page )
           ^
../../build/common_rules.inc:77: recipe for target 'concurrent_queue.o' failed
make[2]: *** [concurrent_queue.o] Error 1
make[2]: Leaving directory '/tmp/RtmpZHlh9r/R.INSTALL186656a92e3c/RcppParallel/src/tbb/build/lib_release'
Makefile:101: recipe for target 'tbb_release' failed
make[1]: *** [tbb_release] Error 2
make[1]: Leaving directory '/tmp/RtmpZHlh9r/R.INSTALL186656a92e3c/RcppParallel/src/tbb/src'
cp: cannot stat 'tbb/build/lib_release/libtbb*.*': No such file or directory
Makevars:74: recipe for target 'tbb' failed
make: *** [tbb] Error 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/usr/local/lib/R/site-library/RcppParallel’
* restoring previous ‘/usr/local/lib/R/site-library/RcppParallel’

The downloaded source packages are in
        ‘/tmp/RtmpMHWqFQ/downloaded_packages’
Warning message:
In install.packages("RcppParallel", repos = "http://cloud.r-project.org") :
  installation of package ‘RcppParallel’ had non-zero exit status
```

I'm using ubuntu 16.04 and my computer has 40 cores and 256G mem.
My gcc version check gives me 
```
>>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 6.3.0-18ubuntu2~16.04' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170519 (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04)
```

Please tell me if you need more informations.
Maybe specific informations you need more.

Thank you very much for the help.

**Comment by eddelbuettel** [comment]
You need to look at the error messages and dig in to see what the reason for the error is.

From here I cannot tell why it would fail.

**Comment by Woong-jae-Jung** [comment]
Thanks for the kind replies eddelbuettel!
I'll keep working on the error messages I get and tell if I solve it.

Again, thank you very much :)

**Comment by eddelbuettel** [comment]
Just to cover the obvious?  You _can_ compile other packages from source, correct?

**Comment by Woong-jae-Jung** [comment]
Yes, other packages compile well from source.
For example

```
R -e 'install.packages("Rcpp", repos="http://cloud.r-project.org")'

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("Rcpp", repos="http://cloud.r-project.org")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'http://cloud.r-project.org/src/contrib/Rcpp_0.12.15.tar.gz'
Content type 'application/x-gzip' length 3762481 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Date.cpp -o Date.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Module.cpp -o Module.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Rcpp_init.cpp -o Rcpp_init.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c api.cpp -o api.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c attributes.cpp -o attributes.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c barrier.cpp -o barrier.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o Rcpp.so Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/Rcpp/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (Rcpp)

The downloaded source packages are in
        ‘/tmp/RtmpVPahiG/downloaded_packages’
```

Rcpp compiles well.

**Comment by eddelbuettel** [comment]
Thanks for that. I am right now out of ideas about why eg Rcpp compilation works and what else is missing.  The semaphore message above suggest you `libc6-dev` installed, I presume you have that?  RcppParallel ties over a little more to system resources but I presume `configure` would have failed ...

**Comment by Woong-jae-Jung** [comment]
Yes, I have checked libc6-dev installed, and it was installed already..

I am going to search deeper for the error messages and tell you if I get anything.
Thanks

**Comment by eddelbuettel** [comment]
We can also go back to the basic Docker container -- I just installed `r-cran-rcpp` there (beyond what the basic Ubuntu container already had) and then the RcppParallel installation pulled in package BH.  Nothing else was added...

**Comment by kevinushey** [comment]
This is the header that provides (POSIX) semaphores, which I think are used by TBB:

http://pubs.opengroup.org/onlinepubs/009695399/basedefs/semaphore.h.html

Is it possible that your system is missing these headers for some reason?

**Comment by eddelbuettel** [comment]
But that is why we covered `libc6-dev` before:

```sh
edd@rob:~$ dpkg -S /usr/include/semaphore.h 
libc6-dev:amd64: /usr/include/semaphore.h
edd@rob:~$ 
```

**Comment by kevinushey** [comment]
This sound related to https://github.com/rstudio/httpuv/issues/110. From Winston:

> The GSNAP/GMAP copy of semaphore.h is somehow getting installed to /usr/local/include. Putting a file in /usr/local/include that has the same name as a standard C header is a bad idea in general.

What is the output of

```
locate semaphore.h
```

on your system? I suspect you might have a version at `/usr/local/include/semahore.h` masking the 'real' version.

**Comment by wch** [comment]
We finally figured out the root cause of this problem. The installer for a a particular version of the GMAP/GSNAP did put the files in the wrong place, although it appears to be fixed in more recent versions. More info here: https://github.com/rstudio/httpuv/issues/110#issuecomment-372879753
